### ISSUE TITLE
Feature Request: Don't load imagemin plugins if their options are set to null

### ISSUE THREAD

**Issue by QWp6t** [Klathmon/imagemin-webpack-plugin#10]
In the same way that [if `pngquant` is set to `null`, it won't load `imageminPngquant()`](https://github.com/Klathmon/imagemin-webpack-plugin/blob/e98f0f626b4428ef22c00ea28c4801c062a71925/src/index.js#L42), I think it would be cool to have that logic for the remaining 4 plugins that are loaded by default.

This is trivial to do from a coding perspective; just create a method that takes an imagemin plugin and its options as method arguments and then push to `this.options.imageminOptions.plugins` if the plugin options argument is not null. I can submit a PR if you're open to the idea.

Thoughts?

**Comment by Klathmon** [comment]
I'm actually on vacation currently, so I'm gonna look at this Monday or Tues next week.

**Comment by Klathmon** [comment]
I love this idea and I added it to the plugin starting with version 1.1.2

I also did a bunch of other arch changes to get ready for some changes I want to do in the future.
