### ISSUE TITLE
jpegs are broken

### ISSUE THREAD

**Issue by k1sul1** [Klathmon/imagemin-webpack-plugin#100]
Whenever I run the production build, my background images (referenced from CSS / Stylus) stop working. In this particular project I only have 3 background images, all jpegs, and they're all broken.

```
new Imagemin({
  disable: env !== 'production',

  optipng: {
    // https://github.com/imagemin/imagemin-optipng
    optimizationLevel: 3,
  },

  gifsicle: {
    // https://github.com/imagemin/imagemin-gifsicle
    optimizationLevel: 2,
  },

  jpegtran: {
    // https://github.com/imagemin/imagemin-jpegtran
    arithmetic: true,
    progressive: true,
  },
  // jpegtran: null,

  svgo: {
    plugins: [
      { removeScriptElement: true },
      { removeViewBox: false },
      { removeDimensions: true },
    ],
  },
}),
```
(Full config here: https://github.com/k1sul1/wordpress-theme-base/blob/master/config/webpack.shared.js#L192)

If I disable jpegtran, they magically start working again.

This is what it starts with.
![sample image](https://user-images.githubusercontent.com/2719615/65840139-dcd4c880-e31d-11e9-84c8-ff5ecf2e3239.jpg)

And this is what it looks like when I try to view it with Chrome or Firefox. _That was a lie._ It doesn't render at all.
![31ee9f1f1c85733dc96452345168b347](https://user-images.githubusercontent.com/2719615/65840161-1c9bb000-e31e-11e9-9c18-394a34823f09.jpg)

Here's where it gets interesting. I can see the file just fine in KDE, and opening it in Gwenview works as well, but it doesn't work in a browser. Reuploaded the same file, the difference between these two are that the first one was saved through Chrome, and the latter from KDE.

![31ee9f1f1c85733dc96452345168b347](https://user-images.githubusercontent.com/2719615/65840188-71d7c180-e31e-11e9-87e4-6000c253990b.jpg)

**Comment by k1sul1** [comment]
If I set arithmetic to false, then they work. So I guess that option spesifically is broken. Arithmetic doesn't work even if I disable progressive.

**Comment by Klathmon** [comment]
Sorry this is most likely a problem with the imagemin plugin you are using to optimize (in this case jpegtran). This plugin is just plumbing to get imagemin working in webpack, and imagemin is just plumbing to get the various optimizers (like pngquant and jpegtran) working.


It sounds like you are going to want to look at either imagemin, imagemin-jpegtran, or the jpegtran project itself for this bug. I'm guessing it's the last one, but I don't know for sure.
