### ISSUE TITLE
BUG: Use imagemin-jpegtran instead of jpegtran-bin

### ISSUE THREAD

**Issue by trollepierre** [Klathmon/imagemin-webpack-plugin#108]
You probably want imagemin-jpegtran instead.

https://github.com/imagemin/jpegtran-bin#jpegtran-bin-

**Comment by Klathmon** [comment]
We use imagemin-jpegtran and not jpegtran-bin.

See [here](https://github.com/Klathmon/imagemin-webpack-plugin/blob/master/package.json) in our package.json

**Comment by trollepierre** [comment]
sorry, I am using the v2.4.2. Since v3.0.0 is in beta.
Any update for v3.0.0?

**Comment by Klathmon** [comment]
Even in the 2.4.2 version [we are still using imagemin-jpegtran](https://github.com/Klathmon/imagemin-webpack-plugin/blob/c9be21163ab8c698f19ace924249287d93a7de99/package.json)


And I hope to get the next v3 beta out today which will include some much needed bugfixes and some optional better logging, and i'll promote it to a full release once i get some feedback that it's working correctly from a few people.
