### ISSUE TITLE
Limit the number of concurrent imagemin processes to the number of CPUs

### ISSUE THREAD

**Issue by Klathmon** [Klathmon/imagemin-webpack-plugin#11]
Right now it will spawn an imagemin process for every single image in the asset array all at once, and will wait until they all complete to move on.

This is fine when you only have a handful of images, but when you have 100+ it can overwhelm the system.

Adding a throttling system that can use something like `os.cpus().length` to determine the number of cores on the machine and limiting the number of running operations to that amount will reduce the contention and will make the whole process easier.

This should also include a way to set the `maxConcurrency` via the options object to override the default of "number of CPUs"

**Comment by chrishelgert** [comment]
i could look at it :)

**Comment by Klathmon** [comment]
all implemented thanks to @chrishelgert! Closing this now, will be cut as version 1.2.0
