### ISSUE TITLE
Wrong async-throttle version is used

### ISSUE THREAD

**Issue by evgeniybilyk** [Klathmon/imagemin-webpack-plugin#13]
Author of https://github.com/zeit/async-throttle/ did update his package with changes
fixing Babel 'use strict' and 'let' block scope usage, but didn't bumped package version.

Here is https://github.com/zeit/async-throttle/pull/5 fixing this issue.

This is affecting npm version of your package too.

Please use zeit/async-throttle@0.0.2 after version bump.

Can provide pull request, if zeit merge this changes.

Thanks.

**Comment by Panda-ref** [comment]
He also didn't published his updated 0.0.1 version. It breaks things here.

**Comment by Klathmon** [comment]
Sorry about this everyone. I generally try to vet dependencies better than this.

I'm moving the async-throttle dependency to a specific commit tag for now, and i'll look into replacing the library with something more mature and well-tested in the future.

**Comment by Klathmon** [comment]
Fixed in release v1.2.1

**Comment by Panda-ref** [comment]
many thanks
