### ISSUE TITLE
Use `optionalDependencies` for imagemin plugins

### ISSUE THREAD

**Issue by evilebottnawi** [Klathmon/imagemin-webpack-plugin#14]
Why?
1. It reduces the size of the package (including dependencies).
2. Lack of packets that are not using in the application (inside `node_modules`).
3. Faster loading plugin (`require`, `import`).
4. We enable the user to decide which plugins to use the usual options.
5. No need to keep track of versions of plug-ins and constantly update them.

**Comment by Klathmon** [comment]
How would this work?

IIRC `optionalDependencies` will always try to install the dependency, but if it fails it will continue without failing.

I had thought about not including anything but stock imagemin and letting the user provide all plugins, but that's a bad UX as requiring users to install several packages to just use this is a pain and makes the learning curve steeper.

**Comment by evilebottnawi** [comment]
@Klathmon well leave it at that :smile:
