### ISSUE TITLE
Can we change `emit` event on `after-emit` event

### ISSUE THREAD

**Issue by evilebottnawi** [Klathmon/imagemin-webpack-plugin#19]
Why?
Some plugins on the event `emit` generate files (some images), also many people use` copy-webpack-plugin` which it copies on this event. If `copy-webpack-plugin` plugin is place after `imagemin-webpack-plugin` images are not compressed.

**Comment by Klathmon** [comment]
Would you be able to make this change and test it then make a PR?

I have no issues with it, and the after-emit seems like the event this should actually be running on, but I'm not in a place where I'll be able to work on this for a few days at least.

**Comment by Klathmon** [comment]
I'm going to close this as another PR was just merged that shows how to use this correctly with `copy-webpack-plugin`
