### ISSUE TITLE
Support `filename` option as interpolate name

### ISSUE THREAD

**Issue by evilebottnawi** [Klathmon/imagemin-webpack-plugin#24]
Be good use https://github.com/webpack/loader-utils#interpolatename

Why?

I am using `copy-webpack-plugin` also `url-loader` and `file-loader` and if i use `[hash].[ext]`, i get invalid hash because first added hash then optimize image and it is bad. I can do PR if you accept this.

**Comment by Klathmon** [comment]
I'd welcome a PR for this no problem!

**Comment by Klathmon** [comment]
I'm gonna close this now, feel free to comment or open another if you need anything else!
