### ISSUE TITLE
Support unquoted attributes

### ISSUE THREAD

**Issue by vzaidman** [Klathmon/imagemin-webpack-plugin#25]
if you have svgs with unquoted attributes such as:
`xmlns="http://www.w3.org/2000/svg" width=20px height=20px`

The error: `Error in parsing SVG: Unquoted attribute value` is emitted.

I've created a loader to temporary fix this:
https://www.npmjs.com/package/xml-fix-loader

```
{
  test: /\.svg$/,
  use: [
    { loader: 'file-loader' },
    { loader: 'xml-fix-loader' }
  ]
}
...
plugins: [
  ...
  new ImageminPlugin()
]
```
Also opened a bug on `svgo`:
https://github.com/svg/svgo/issues/678

**Comment by Klathmon** [comment]
Unfortunately there is nothing I can do to to fix this in my package.

Thanks for making an issue with SVGO, and I'll add a note about this to the readme as I think this actually fixes another issue I have open here.

I appreciate the work!
