### ISSUE TITLE
the plugin slows rebuilds

### ISSUE THREAD

**Issue by vzaidman** [Klathmon/imagemin-webpack-plugin#26]
im running with this configs:
```
new ImageminPlugin({
      svgo: {
        plugins: [
          {convertPathData: false}
        ]
      }
    })
```
on webpack 1, i see the following steps, even if no image (and no code) have been changed:
some seconds of "optimizing assets" and then some seconds of "emiting" (together more than 10.)

isn't there a cache on these operations?

about running the plugin only in production- i prefer the development environment to be as close as possible to production. if the plugin can compress all the images only once, there should be no problem with this.

**Comment by Klathmon** [comment]
There is no cache on anything currently.

I would be open to a PR that adds one, but the next few weeks are going to be pretty busy for me so I won't have time to implement it myself.

**Comment by RehanSaeed** [comment]
The cache should be saved to disk so it can be checked in to Git and shared across a team. Repeatedly minifying an image should be avoided.

**Comment by Klathmon** [comment]
I'm not sure I'm open to that.

That would require a lot more work and fragility introduced into the application needing a persistent cache that can be re-read in and gracefully deal with plugin updates, config changes, image changes and other things.

It's a ton of complexity which IMO would be better solved by an alternate plugin which is dedicated to that use case.

**Comment by RehanSaeed** [comment]
I'm new to Webpack, I know Gulp has cache plugins like you describe. Does something like that exist?

**Comment by Rodrigoleon** [comment]
@RehanSaeed also pretty new to Webpack, but (this)[https://webpack.js.org/loaders/cache-loader/] might be what you are looking for. There are a few other good plugins/loaders/docs [here](https://github.com/webpack-contrib/awesome-webpack#webpack-plugins).

I'm trying to decide which imagemin plugin to use. This one or (this one)[https://github.com/thetalecrafter/img-loader]. Any pros/cons? :)

**Comment by sotaan** [comment]
@Rodrigoleon I will use this one if I were you. It's in the FAQ part:

> Why not use image-webpack-loader?
> Because I had other things like the favicons-webpack-plugin and responsive-loader that were generating images that I couldn't have image-webpack-loader optimize. This plugin will optimize ANY images regardless of how they were added to webpack. Plus image-webpack-loader is currently using an older version of imagemin.

**Comment by Klathmon** [comment]
@Rodrigoleon 

Well personally I'd use my plugin (but I might be a bit biased!)

In reality, it depends on what you need. If you need to work with things like the inline-image features of url-loader, then `image-webpack-loader` might be your best bet as this plugin still has issues there.

But if you are just looking for something to minify your images, my plugin will get you there in an easier way (in my opinion).

Anyway I'm closing this issue for now, as it doesn't seem like anything hugely productive will happen (feel free to keep talking, it's just the open issue is bothering me 😄).
