### ISSUE TITLE
Error dyld: Library not loaded

### ISSUE THREAD

**Issue by MatteoGabriele** [Klathmon/imagemin-webpack-plugin#28]
I randomly have this issue when trying to optimize pngs

`Error: dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib`

I'm almost sure that is not due to your implementation but because of the `libpng` library, but do you know why this happening **( not in all machines )** ?

Thanks in advance!

cheers! :)

**Comment by Klathmon** [comment]
Okay, I'm guessing this is on OSX? What version (and maybe hardware)?

And when you say it's random, does it happen consistently? do you need to do anything specific to get it to stop?

**Comment by MatteoGabriele** [comment]
When I say randomly I mean that happens to a random machine: for example doesn't occur in my machine, but in other does.

Tested in all macbook pro running macOS Sierra 10.12.3

In my machine for example i didn't have to do it, but in others this fix it `brew install libpng`

thanks!

**Comment by Klathmon** [comment]
Most likely some other package you have installed already installed libpng as a dependency.

Glad you got it sorted out!

**Comment by MatteoGabriele** [comment]
But why `libpng` is not installed when I install `imagemin-webpack-plugin` since it has pngquant as an option?

**Comment by Klathmon** [comment]
I'm not sure. pngquant might rely on the OS's package manager to install libpng, or the compile with node-gyp might have failed (normally more of a problem on windows than other platforms, but it might still happen to them sometimes).
