### ISSUE TITLE
How to make 'imagemin-webpack-plugin' execute before 'url-loader' ？

### ISSUE THREAD

**Issue by xxssww0258** [Klathmon/imagemin-webpack-plugin#31]
I want to compress images then turn base64

**Comment by Klathmon** [comment]
There is already an issue for this open at #22 

The summary is that it's not going to work with url-loader's base64 images right now. You could always setup imagemin-loader to run for those images, and this plugin to run for the rest, or you can just stick to using imagemin-loader for now until we solve that issue.

**Comment by xxssww0258** [comment]
thank you
