### ISSUE TITLE
Testing new beta before release

### ISSUE THREAD

**Issue by Klathmon** [Klathmon/imagemin-webpack-plugin#33]
Hey @natedanner, (and anyone else willing!)

Would you be able to install version 1.5.0-beta.1 for me and make sure it works in your environment?

I rewrote some aspects of it and want to ensure it doesn't break in someone else's setup before pushing it to everyone.

**Comment by natedanner** [comment]
I'll try to test it tonight, tomorrow at latest.

**Comment by Klathmon** [comment]
No rush! I just wanted to make sure that part of the code works before pushing everything out as stable!

**Comment by natedanner** [comment]
Hey, @Klathmon. Tested and working in my setup running `1.5.0-beta.1` :clinking_glasses:

**Comment by Klathmon** [comment]
Fantastic, thanks a ton!

I'll push this out as 1.5.0 some time this weekend most likely.
