### ISSUE TITLE
gifsicle throw new Error('not implemented')

### ISSUE THREAD

**Issue by Dugnist** [Klathmon/imagemin-webpack-plugin#35]
module `gifsicle`
in `_stream_transform.js:159`
`throw new Error('not implemented');`

linux ubuntu 16

[<img src="http://joxi.ru/nAyx3D0uYlYy42.jpg">](http://joxi.ru/nAyx3D0uYlYy42.jpg)

**Comment by Klathmon** [comment]
Wow I can't say I've ever seen this before.

What version are you using? and can you post the webpack config you are using (or the relevant parts that involve this plugin)?

**Comment by Dugnist** [comment]
https://github.com/Dugnist/html5-boilerplate

**Comment by Klathmon** [comment]
I can't seem to reproduce this...

What version of node.js are you using?

**Comment by Klathmon** [comment]
Closing this ticket in favor of #39 as they seem to be the same issue.
