### ISSUE TITLE
Progressive JPEG if > 10Kb

### ISSUE THREAD

**Issue by shkarupa-alex** [Klathmon/imagemin-webpack-plugin#36]
Could you add option to address this issue https://github.com/imagemin/imagemin/issues/142 ?

**Comment by Klathmon** [comment]
Thanks for the idea!

I'll add 2 config options. `minFileSize` and `maxFileSize`. Then you can include 2 copies of the plugin into your config, one for files over 10kb, and one for files under 10kb.

**Comment by Klathmon** [comment]
I just added this and released version 1.5.1

You can see how to use it [here](https://github.com/Klathmon/imagemin-webpack-plugin#optionsminfilesize).
