### ISSUE TITLE
gifsicle postinstall fails

### ISSUE THREAD

**Issue by LittleHendrix** [Klathmon/imagemin-webpack-plugin#39]
Hi there,
I'm experiencing some issues with installing the imagemin-webpack-plugin. All the add-on modules - gifsicle, pngquant, optipng, jpegtran, .etc returns `tunneling socket could not be established, statusCode=403` message when postinstall is called. 

![error](https://user-images.githubusercontent.com/1037065/30163622-800da0c4-93d1-11e7-9c01-fb64fc81ef28.png)

This only happens on my work PC (windows 7 64bit) which is sitting behind a proxy server. Everything works perfectly fine on my home PC. See screenshot below for my .npmrc settings:

![npmrc](https://user-images.githubusercontent.com/1037065/30163902-9fa614f6-93d2-11e7-92d6-2219233bcd7a.png)

* OS: Windows 7 Enterprise
* NodeJS: **v6.11.3**
* NPM: **3.10.10**

I've also set system environment variables for both `HTTP_PROXY` and `HTTPS_PROXY`. All other NPM packages seem to be fine with the existing setup. Not sure what else I need to do to fix this. Will you be able to help please? Thank you!

**Comment by Klathmon** [comment]
Are you able to install gifsicle directly?

`npm install gifsicle@3.0.4`

**Comment by LittleHendrix** [comment]
Yeah, I was able to install `imagemin-pngquant` and `imagemin-gifsicle` without any issues.

![capture](https://user-images.githubusercontent.com/1037065/30173472-b3093042-93ef-11e7-8bc6-68c643bf547c.PNG)

**Comment by LittleHendrix** [comment]
Apologies, I might have spoken too soon. When I uninstalled `imagemin-webpack-plugin` and tried a clean install of `gifsicle` and I got the same issue as before..

![capture](https://user-images.githubusercontent.com/1037065/30201849-1b57dac0-9474-11e7-985f-c8d23c09025b.PNG)

**Comment by Klathmon** [comment]
That sounds like it's an issue with the gifsicle package.

You might want to check out [this issue here](https://github.com/imagemin/gifsicle-bin/issues/76) which sounds like it's your problem as well.

Or maybe open an issue with the core imagemin package if it's happening with all addons.

In the mean-time, if you want I can make a fork that doesn't include ANY of those addon modules requiring you to manually install each one yourself if you want any, then you can install any that do work and use them until they resolve the issue.

Just let me know if you want it and I can have that branch for you ASAP.

**Comment by LittleHendrix** [comment]
Hi there,
Sorry about the late reply. I will raise an issue on the core imagemin github page. Yeah, if you wouldn't mind creating a package without all the add-ons that'd be fantastic!
Thanks!

**Comment by Klathmon** [comment]
I just created the branch [no-default-plugins](https://github.com/Klathmon/imagemin-webpack-plugin/tree/no-default-plugins) for you.

You should include it in your package.json like this:

    "imagemin-webpack-plugin": "Klathmon/imagemin-webpack-plugin#no-default-plugins"

You will need to manually install any plugins you want yourself and put their options in the `plugins` option in this webpack plugin in order for anything to be optimized/compressed.

**Comment by LittleHendrix** [comment]
Thank you for your help. It is much appreciated!

Cheers!
