### ISSUE TITLE
Plugin breaks Webpack in CircleCI since v1.5.0-beta.1

### ISSUE THREAD

**Issue by kayue** [Klathmon/imagemin-webpack-plugin#41]
Since v1.5.0-beta.1 this plugin somehow breaks Webpack build process in silent since v1.5.0-beta.1. This only happens in my CircleCI environment (node 6.1.0, npm 5.3.0) without any error message.

I have settings like this:

        new ImageminPlugin({
            externalImages: {
                sources: [...]
            }
        }),
        new ExtractTextPlugin({
            filename: '[name].css',
        }),

The problem is the `ExtractTextPlugin` doesn't execute after I upgraded to v1.5.0-beta.1. 

From my test it works after I remove all options in the `ImageminPlugin`

It only happens in version `v1.5.0-beta.1` and after. I switched back to `v1.5.0-beta.0` and it works fine.

**Comment by Klathmon** [comment]
I just released [V1.6.0-beta.1](https://github.com/Klathmon/imagemin-webpack-plugin/releases/tag/v1.6.0-beta.1), which works for me on CircleCI.

I don't exactly know what the problem was, but 1.6 was a big refactoring, so I might have inadvertently fixed the issue!
