### ISSUE TITLE
Matching every file in a folder recursively

### ISSUE THREAD

**Issue by damianobarbati** [Klathmon/imagemin-webpack-plugin#42]
How can we properly set `test` to match any file in a folder recursively without knowing how many subfolders exists in it? 
I.E. `test: 'build/**/**/*.(jpe?g|png|gif|svg)'`
But I don't know if the files will be in 1st, 2nd, 3rd and so on level of nesting

**Comment by Klathmon** [comment]
A "globstar" is a special matcher in a glob that matches "zero or more directories"

So `build/**/*.png` would match:

* `build/thing.png`
* `build/stuff/thing.png`
* `build/stuff/things/thing.png`
* etc...

The test option can also be an array of globs, so you could include multiple globs in there.
