### ISSUE TITLE
Root directory scratch files

### ISSUE THREAD

**Issue by r4j4h** [Klathmon/imagemin-webpack-plugin#5]
Hi there, I am enjoying your plugin!

I've noticed that when running webpack with ImageminPlugin engaged, I get scratch files generated in my root directory with GUIDs for names and no extensions:

`7bad0c4e-7322-4118-9d71-30b2b8ca5617`
`ef68099e-3ef9-4dbd-81c2-3bc4204f2cff`

and the like.

For what it's worth I *think* it scales with the number of entry points, but I am not confident on that as fact.

My sincere apologies if it's from some combination of plugins, I've reduced it down to extract text plugin and style-loader / css-loader / sass-loader. It definitely goes away if I set `disable: true`, so that is what brings me here.

**Comment by Klathmon** [comment]
Hmm, I haven't noticed that, but then again I don't pay too much attention to the output folder. I can take a look at this later today or tomorrow. Would you be able/willing to post your webpack config somewhere?

**Comment by EmmanuelBeziat** [comment]
I have the same problem, and people using image-loader have it too. 

https://github.com/tcoopman/image-webpack-loader/issues/41
