### ISSUE TITLE
Does this work with svg-sprite-loader

### ISSUE THREAD

**Issue by RehanSaeed** [Klathmon/imagemin-webpack-plugin#50]
I'm looking into how to use SVG sprites with Webpack using [svg-sprite-loader](https://www.npmjs.com/package/svg-sprite-loader). Would this plugin work alongside it? Would it minify SVG's before being placed in the sprite?

**Comment by Klathmon** [comment]
I don't know why I never got notified of this issue...

But yes it will work with svg sprite loader, but it will minify the resulting sprite it creates, and not each image individually before it gets made into the sprite.

If you want/need each svg minified before it's made into the sprite, [`image-webpack-loader`](https://github.com/tcoopman/image-webpack-loader) will probably be your best bet!
