### ISSUE TITLE
Update to latest imagemin-svgo

### ISSUE THREAD

**Issue by strarsis** [Klathmon/imagemin-webpack-plugin#51]
@Klathmon: Latest imagemin-svgo uses latest svgo which comes with the inlineStyles and prefixIds plugins.

**Comment by Klathmon** [comment]
This should be released in the next version, but until then you can always pass in null under the `svgo` option, then pass in your own copy of `svgo` in the `plugins` array with the options you want.

**Comment by Klathmon** [comment]
I just released v1.6.0 which includes the newest version of `imagemin-svgo`
