### ISSUE TITLE
File test ignored

### ISSUE THREAD

**Issue by EmeraldWeb** [Klathmon/imagemin-webpack-plugin#52]
Today i updated npm, after this imagemin-webpack-plugin just stopped minify files, after tests and checks I came to the conclusion what plugin ignore file testing.
I have very simple directory :
[issue-imagemin-webpack-plugin.zip](https://github.com/Klathmon/imagemin-webpack-plugin/files/1632301/issue-imagemin-webpack-plugin.zip)

But images are not minified, not in ver. 1.5.2, not in 1.6.0

Thanks for attention, I hope you help me understand what i do wrong or resolve this bug.

**Comment by Klathmon** [comment]
Sorry about that! I'm taking a look right now at what happened. Thanks a ton for the zip, it will make this super easy to figure out.

If you know, what was the last version you remember the plugin working for you?

**Comment by Klathmon** [comment]
Okay, well your first problem is that you are installing `^1.5.2` which is actually installing the latest version of `1.x.x`, which is `1.6.0` If you change that to be `1.5.2` (no caret `^` symbol) in your package.json, it should work for you right now, as that will lock the version to `1.5.2`.


But it looks like there is a problem with the `test` option in the latest version, I should be able to get  this fixed within the hour hopefully, and I can release a new version.

**Comment by Klathmon** [comment]
This was fixed in v1.6.1

Sorry about that, it was a typo on my part. Thanks again for the test case, it was a huge amount of help in figuring this out.

**Comment by EmeraldWeb** [comment]
I apologize for my inattention, yes all work good in 1.5.2. Thank you kindly.

**Comment by Klathmon** [comment]
No need to apologise! The test case zip you provided made this a 15 minute fix!
