### ISSUE TITLE
Link for imagemin compatible plugins has no results

### ISSUE THREAD

**Issue by kylemh** [Klathmon/imagemin-webpack-plugin#57]
Thanks a lot for this plugin! I'm trying to get it work and will submit a few issues regarding any difficulties I have.

https://github.com/Klathmon/imagemin-webpack-plugin#optionsplugins

under `options.plugins`

```
type: Array default: []

Include any additional plugins that you want to work with imagemin here. By default the above are included, but if you want (or need to) you can disable them (by setting them to null) and include them yourself here.

A list of possible imagemin plugins can be found here.
```

The here at the end is a link that goes to: https://www.npmjs.com/browse/keyword/imageminplugin

There are 0 results in that search.

**Comment by Klathmon** [comment]
Thanks for the heads up!

Looks like NPM changed their search a while back and is badly redirecting results from it...

I can switch that out with a good one right now.
