### ISSUE TITLE
vulnerability error

### ISSUE THREAD

**Issue by sobolevn** [Klathmon/imagemin-webpack-plugin#60]
Hi, there's a vulnerability error with one of your dependencies.

```
» npx nsp check
npx: installed 115 in 9.19s
(+) 1 vulnerability found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Memory Exposure                                                    │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ tunnel-agent                                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 5 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 0.4.3                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <0.6.0                                                             │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ >=0.6.0                                                            │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ nuxt-imagemin@0.1.2 > imagemin-webpack-plugin@2.1.1 >              │
│            │ imagemin-optipng@5.2.1 > optipng-bin@3.1.4 > bin-build@2.2.0 >     │
│            │ download@4.4.3 > caw@1.2.0 > tunnel-agent@0.4.3                    │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/598                             │
└────────────┴────────────────────────────────────────────────────────────────────┘

```

Related: https://github.com/wemake-services/nuxt-imagemin/issues/2

**Comment by Klathmon** [comment]
I'm going to see what I can do to mitigate it, but i'm pretty sure that unfortunately this has to be fixed upstream in my dependencies.

That being said, it seems there is no instance where user-provided authentication can be used with optipng-bin (which is what is using the bin-build/download packages where this is used), so this vulnerability shouldn't impact anyone because of my plugin (in other words, this plugin, nor any of its dependencies, ever call the vulnerable line of code, so it can't impact us)

**Comment by Klathmon** [comment]
Released as [v2.1.2](https://github.com/Klathmon/imagemin-webpack-plugin/releases/tag/v2.1.2)!

Thanks a ton for the report, the table you included made it MUCH easier to track this down quickly!

**Comment by eamodio** [comment]
@Klathmon For npm users, can you generate a `package-lock.json` file so the version can be bumped there as well? To generate a `package-lock.json`, either start with a clean `node_modules` folder, or a `node_modules` folder containing exactly what is in your yarn.lock, and then run `npm install`, that should generate a new `package-lock.json`

**Comment by Klathmon** [comment]
Can you easily generate a `package-lock.json` file with a pinned dependency-of-a-dependency?

I was under the impression that you couldn't without hand-modifying the `package-lock.json` which I don't want to maintain myself.

**Comment by eamodio** [comment]
I think if you run `npm --depth 9999 update <package>@<version>` it will update the package for all depths of dependencies.
