### ISSUE TITLE
Producing multiple outputs

### ISSUE THREAD

**Issue by talha5389** [Klathmon/imagemin-webpack-plugin#62]
Is it possible to use this to produce 2 outputs for my images e.g. I have image `image1.jpg`. I want to output it in `dist/images/image1.jpg` with plugin `ImageminMozjpeg`. In addition to that, I also want `dist/images/image1.webp` from same source image (image1.jpg).

**Comment by Klathmon** [comment]
That's something that would be better served by other plugins or loaders.

[Webp-loader](https://github.com/kavu/webp-loader/blob/master/README.md) has some information in their readme about how to get both formats out of webpack.

And I'd recommend not having webp-loader do the optimization, and instead let this plugin do it so all the optimization happens in the same place.
