### ISSUE TITLE
Images not being compressed using externalImages

### ISSUE THREAD

**Issue by lp2al** [Klathmon/imagemin-webpack-plugin#65]
Hi there, 

Wondering if anyone could tell me if my code below is correct?

```
new ImageminPlugin({
        externalImages: {
            context: 'src',
            sources: glob.sync('src/images/**/*.jpg'),
            destination: 'assets'
        }
}),
```
The build completes, and any images that I've required in my app are compressed as expected. However, images that are not required are just being copied over to the assets folder. I was under the impression externalImages will compress all images from a given source regardless of being required in my app or not?

Many thanks.
P

**Comment by Klathmon** [comment]
Would you have a full webpack config that you can post? It's not required but it does help debug issues a lot of the time. Specifically I'm asking to make sure you don't have anything else that might be copying the images AFTER ImageminPlugin runs (in other words, imagemin runs and optimizes the images, then another plugin just copies the original ones over top of them)

Also, I know it's a bit of a long shot but make sure the images are actually able to be compressed. If the "optimized" version is larger than the original, it will just copy the original.

**Comment by Klathmon** [comment]
I'm going to close this for now. Please let me know if you need any more assistance!
