### ISSUE TITLE
pngquant error

### ISSUE THREAD

**Issue by beckend** [Klathmon/imagemin-webpack-plugin#8]
Getting this error everytime i try with pngquant:
`optimizationError: Command failed: /Users/linken/Coding/REACT/project-react/node_modules/pngquant-bin/vendor/pngquant --output /var/folders/_2/5800gryd57nclgrrbwt64hj00000gn/T/471e1ad9-588c-4683-8ed1-82f0b9eae97c /var/folders/_2/5800gryd57nclgrrbwt64hj00000gn/T/850dd1ba-4813-4525-a9e7-a1f2fd487f97 --quality 100`
The binary exist and works fine, compiles fine without pngquant option.

**Comment by Klathmon** [comment]
Can you try installing `imagemin-cli` standalone, and the pngquant plugin, and try optimizing that image manually? ( you can install them with `npm install imagemin-cli imagemin-pngquant` and can run it with something *kinda like* `imagemin --plugin=pngquant ./filename.png > outputFile.png

**Comment by beckend** [comment]
That's pretty tough, I have only 2 images, and they work fine, it then means that the vendor plugins/css is including images which causes this error, it's too cryptic to trace. Thanks anyways.
