### ISSUE TITLE
Can You Give More Detailed Example?

### ISSUE THREAD

**Issue by webdev20** [Klathmon/imagemin-webpack-plugin#80]
I am a new user of this plugin and feel confused. I don't know how to set the settings of jpegtran, gifsicle, should I use `optimizationLevel` or `quality` property, etc. There are only links to the imagemin plugins. That is very confusing because there is no proper documentation there too.

Can you give more detailed examples or explanations on how to use each?

**Comment by Klathmon** [comment]
Yeah sorry, documentation is one area that I'm trying to improve!


So the basic idea of this plugin is that it will automatically optimize all images it sees by default. So simply doing this in webpack will work for most simpler use cases:

```
module.exports = {
  plugins: [
    new ImageminPlugin({
      disable: process.env.NODE_ENV !== 'production' // Disable during development
    })
  ]
}
```

That will optimize images with good defaults in production mode only.


If you want to customize the various optimizers, you can pass in the options that each plugin takes by it's name. so `pngquant: { quality: '95-100' }` will tell `pngquant` to optimize to that quality level. Each link to a plugin should have documentation on what kind of object it wants and what each object does.

The options for each plugin are normally listed under the "options" subheading on each plugin page (i personally hate the way they are all laid out, but at least they are somewhat consistent!).

So for [imagemin-optipng](https://github.com/imagemin/imagemin-optipng) for example, the `optimizationLevel` property will set the optimization level, and it would be used like this:


```
module.exports = {
  plugins: [
    new ImageminPlugin({
      disable: process.env.NODE_ENV !== 'production', // Disable during development
      optipng: { optimizationLevel: 7 }
    })
  ]
}
```

Hopefully that answers your question!
