### ISSUE TITLE
Output directory and file name

### ISSUE THREAD

**Issue by johndugan** [Klathmon/imagemin-webpack-plugin#9]
Hi there,

Thanks for the great plugin! I have two questions:

1. Is it possible to define the output path for the images? Currently the images are output to the root directory.

2. Is is possible to define a custom name/hash for the output files?

I played around with my webpack config a bit and couldn't seem to resolve these two issues. I am new to webpack, so perhaps I am doing something wrong.

**Comment by Klathmon** [comment]
Thanks! Those things are actually both handled in webpack and other loaders, not in this plugin.

You specify the filename in the loader's config you are using to load the images. Most use file-loader. For example, this is the file-loader string from one of my projects:

    file-loader?hash=sha1&digest=hex&name=[name]-[hash].[ext]

That will rename the file to be a hex of an sha1 hash of the file. You can look at file-loader's docs for more info there.

This can also be used to put images in a different folder, so if you changed that last part to `name=./images/[name]-[hash].[ext]` it will put all images into an `image` folder in your output path.

**Comment by johndugan** [comment]
Ahhh - thanks.

I've been using file-loader. Last night, I _tried_ setting up responsive-loader with this plugin. I just removed responsive-loader and this plugin works great. I still have those issues above, but it looks like my questions need to be directed to the responsive-loader issues.

Thanks for the fast response.

**Comment by Klathmon** [comment]
I actually use it fine with responsive-loader. here's that part of my config:

    loaders: [
        'responsive?' + [100, 250, 500, 750, 1000, 2500, 5000, 10000].map((size) => `sizes[]=${size}`).join(','),
        'file-loader?hash=sha1&digest=hex&name=[name]-[hash].[ext]'
      ]

It's in ES6 so heads up about that, but I figured i'd at least drop it here for you.

One thing to watch out for, is i'm excluding SVG images from this loader, as it messes with responsive-loader (i don't remember what it does exactly, but I remember needing to exclude SVG specifically)

**Comment by johndugan** [comment]
_Very_ helpful!

Much cleaner too with the map implementation. Sometimes things like webpack feel so foreign at first that I forget it's just JavaScript.

**Comment by Klathmon** [comment]
Webpack has the worst documentation I've seen in a project of its size, and the formats it uses are pretty out there (I mean really, query strings?), So I don't blame ya for not getting it.

It took me 3 seperate attempts to get something useful working with it before I started getting comfortable.

**Comment by johndugan** [comment]
Indeed. It's been very difficult for me to be productive. The time I've spent understanding boilerplate makes me sick...

Thanks again for the help!
